--------------------------------------------------------
--  파일이 생성됨 - 토요일-8월-14-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CB_APPLICATE
--------------------------------------------------------

  CREATE TABLE "CB_APPLICATE" 
   (	"AP_NO" NUMBER, 
	"PR_NO" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"AP_PRICE" NUMBER, 
	"AP_DATE" DATE DEFAULT sysdate, 
	"AP_PAY" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_BOARD
--------------------------------------------------------

  CREATE TABLE "CB_BOARD" 
   (	"BOARD_ID" NUMBER, 
	"BOARD_TITLE" VARCHAR2(200 BYTE), 
	"BOARD_CONTENT" VARCHAR2(1000 BYTE), 
	"BOARD_DATE" DATE DEFAULT sysdate, 
	"BOARD_HIT" NUMBER DEFAULT 0, 
	"BOARD_CMT_NUM" NUMBER DEFAULT 0, 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_CMT
--------------------------------------------------------

  CREATE TABLE "CB_CMT" 
   (	"CMT_NO" NUMBER, 
	"CMT_CONTENT" VARCHAR2(500 BYTE), 
	"CMT_DATE" DATE DEFAULT sysdate, 
	"BOARD_ID" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_CMTS
--------------------------------------------------------

  CREATE TABLE "CB_CMTS" 
   (	"CMTS_NO" NUMBER, 
	"CMTS_CONTENT" VARCHAR2(500 BYTE), 
	"CMTS_DATE" DATE DEFAULT sysdate, 
	"CMT_NO" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_CS
--------------------------------------------------------

  CREATE TABLE "CB_CS" 
   (	"CS_NO" NUMBER, 
	"CS_TITLE" VARCHAR2(200 BYTE), 
	"CS_CONTENT" VARCHAR2(1000 BYTE), 
	"CS_DATE" DATE DEFAULT sysdate, 
	"CS_CMT_NUM" NUMBER DEFAULT 0, 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_CS_CMT
--------------------------------------------------------

  CREATE TABLE "CB_CS_CMT" 
   (	"CS_CMT_NO" NUMBER, 
	"CS_CMT_CONTENT" VARCHAR2(200 BYTE), 
	"CS_CMT_DATE" DATE DEFAULT sysdate, 
	"USER_ID" VARCHAR2(50 BYTE), 
	"CS_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_NOTICE
--------------------------------------------------------

  CREATE TABLE "CB_NOTICE" 
   (	"N_NO" NUMBER, 
	"N_DATE" DATE DEFAULT sysdate, 
	"N_CONTENT" VARCHAR2(1000 BYTE), 
	"N_TITLE" VARCHAR2(200 BYTE), 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_PURCHASE
--------------------------------------------------------

  CREATE TABLE "CB_PURCHASE" 
   (	"PR_NO" NUMBER, 
	"PR_CATEGORY" VARCHAR2(50 BYTE), 
	"PR_TITLE" VARCHAR2(200 BYTE), 
	"PR_MIN" NUMBER, 
	"PR_MAX" NUMBER, 
	"PR_STARTDATE" DATE, 
	"PR_ENDDATE" DATE, 
	"PR_PRICE" NUMBER, 
	"PR_PHOTO1" VARCHAR2(300 BYTE), 
	"PR_PHOTO2" VARCHAR2(300 BYTE), 
	"PR_PHOTO3" VARCHAR2(300 BYTE), 
	"PR_CONTENT" VARCHAR2(2000 BYTE), 
	"PR_PEOPLE" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_USER
--------------------------------------------------------

  CREATE TABLE "CB_USER" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_PW" VARCHAR2(50 BYTE), 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"USER_NICKNAME" VARCHAR2(40 BYTE), 
	"USER_EMAIL" VARCHAR2(100 BYTE), 
	"USER_PHONE" VARCHAR2(40 BYTE), 
	"USER_PROFILE" VARCHAR2(300 BYTE), 
	"USER_AUTHOR" VARCHAR2(20 BYTE), 
	"USER_STATE" VARCHAR2(1 BYTE) DEFAULT 'A'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CB_WISH
--------------------------------------------------------

  CREATE TABLE "CB_WISH" 
   (	"W_NO" NUMBER, 
	"PR_NO" NUMBER, 
	"USER_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_APPLICATE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_APPLICATE_PK" ON "CB_APPLICATE" ("AP_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_BOARD_PK" ON "CB_BOARD" ("BOARD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_COMMENT_PK" ON "CB_CMT" ("CMT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_COMMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_COMMENTS_PK" ON "CB_CMTS" ("CMTS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_CS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_CS_PK" ON "CB_CS" ("CS_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_CS_CMT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_CS_CMT_PK" ON "CB_CS_CMT" ("CS_CMT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_NOTICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_NOTICE_PK" ON "CB_NOTICE" ("N_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_PURCHASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_PURCHASE_PK" ON "CB_PURCHASE" ("PR_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_USER_PK" ON "CB_USER" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CB_WISH_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CB_WISH_PK" ON "CB_WISH" ("W_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CB_APPLICATE
--------------------------------------------------------

  ALTER TABLE "CB_APPLICATE" ADD CONSTRAINT "CB_APPLICATE_PK" PRIMARY KEY ("AP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_APPLICATE" MODIFY ("AP_PAY" NOT NULL ENABLE);
  ALTER TABLE "CB_APPLICATE" MODIFY ("AP_PRICE" NOT NULL ENABLE);
  ALTER TABLE "CB_APPLICATE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_APPLICATE" MODIFY ("PR_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_APPLICATE" MODIFY ("AP_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_BOARD
--------------------------------------------------------

  ALTER TABLE "CB_BOARD" ADD CONSTRAINT "CB_BOARD_PK" PRIMARY KEY ("BOARD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_BOARD" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_BOARD" MODIFY ("BOARD_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CB_BOARD" MODIFY ("BOARD_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_CMT
--------------------------------------------------------

  ALTER TABLE "CB_CMT" ADD CONSTRAINT "CB_COMMENT_PK" PRIMARY KEY ("CMT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_CMT" MODIFY ("CMT_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_CMT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_CMT" MODIFY ("BOARD_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_CMT" MODIFY ("CMT_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_CMTS
--------------------------------------------------------

  ALTER TABLE "CB_CMTS" ADD CONSTRAINT "CB_COMMENTS_PK" PRIMARY KEY ("CMTS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_CMTS" MODIFY ("CMTS_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_CMTS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_CMTS" MODIFY ("CMT_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_CMTS" MODIFY ("CMTS_CONTENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_CS
--------------------------------------------------------

  ALTER TABLE "CB_CS" ADD CONSTRAINT "CB_CS_PK" PRIMARY KEY ("CS_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_CS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_CS" MODIFY ("CS_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CB_CS" MODIFY ("CS_TITLE" NOT NULL ENABLE);
  ALTER TABLE "CB_CS" MODIFY ("CS_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_CS_CMT
--------------------------------------------------------

  ALTER TABLE "CB_CS_CMT" ADD CONSTRAINT "CB_CS_CMT_PK" PRIMARY KEY ("CS_CMT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_CS_CMT" MODIFY ("CS_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_CS_CMT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_CS_CMT" MODIFY ("CS_CMT_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CB_CS_CMT" MODIFY ("CS_CMT_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_NOTICE
--------------------------------------------------------

  ALTER TABLE "CB_NOTICE" ADD CONSTRAINT "CB_NOTICE_PK" PRIMARY KEY ("N_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_NOTICE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_NOTICE" MODIFY ("N_TITLE" NOT NULL ENABLE);
  ALTER TABLE "CB_NOTICE" MODIFY ("N_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CB_NOTICE" MODIFY ("N_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_PURCHASE
--------------------------------------------------------

  ALTER TABLE "CB_PURCHASE" ADD CONSTRAINT "CB_PURCHASE_PK" PRIMARY KEY ("PR_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_PEOPLE" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_PHOTO1" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_PRICE" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_MAX" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_MIN" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_TITLE" NOT NULL ENABLE);
  ALTER TABLE "CB_PURCHASE" MODIFY ("PR_CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_USER
--------------------------------------------------------

  ALTER TABLE "CB_USER" ADD CONSTRAINT "CB_USER_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_USER" MODIFY ("USER_STATE" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_PHONE" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_PW" NOT NULL ENABLE);
  ALTER TABLE "CB_USER" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CB_WISH
--------------------------------------------------------

  ALTER TABLE "CB_WISH" ADD CONSTRAINT "CB_WISH_PK" PRIMARY KEY ("W_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CB_WISH" MODIFY ("W_NO" NOT NULL ENABLE);
  ALTER TABLE "CB_WISH" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CB_WISH" MODIFY ("PR_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CB_APPLICATE
--------------------------------------------------------

  ALTER TABLE "CB_APPLICATE" ADD CONSTRAINT "CB_APPLICATE_FK1" FOREIGN KEY ("PR_NO")
	  REFERENCES "CB_PURCHASE" ("PR_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CB_APPLICATE" ADD CONSTRAINT "CB_APPLICATE_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_BOARD
--------------------------------------------------------

  ALTER TABLE "CB_BOARD" ADD CONSTRAINT "CB_BOARD_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_CMT
--------------------------------------------------------

  ALTER TABLE "CB_CMT" ADD CONSTRAINT "CB_COMMENT_FK1" FOREIGN KEY ("BOARD_ID")
	  REFERENCES "CB_BOARD" ("BOARD_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CB_CMT" ADD CONSTRAINT "CB_COMMENT_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_CMTS
--------------------------------------------------------

  ALTER TABLE "CB_CMTS" ADD CONSTRAINT "CB_COMMENTS_FK1" FOREIGN KEY ("CMT_NO")
	  REFERENCES "CB_CMT" ("CMT_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CB_CMTS" ADD CONSTRAINT "CB_COMMENTS_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_CS
--------------------------------------------------------

  ALTER TABLE "CB_CS" ADD CONSTRAINT "CB_CS_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_NOTICE
--------------------------------------------------------

  ALTER TABLE "CB_NOTICE" ADD CONSTRAINT "CB_NOTICE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_PURCHASE
--------------------------------------------------------

  ALTER TABLE "CB_PURCHASE" ADD CONSTRAINT "CB_PURCHASE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CB_WISH
--------------------------------------------------------

  ALTER TABLE "CB_WISH" ADD CONSTRAINT "CB_WISH_FK1" FOREIGN KEY ("PR_NO")
	  REFERENCES "CB_PURCHASE" ("PR_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CB_WISH" ADD CONSTRAINT "CB_WISH_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "CB_USER" ("USER_ID") ON DELETE CASCADE ENABLE;
